#!/usr/bin/env bash

################################################################################
# bootstrap
#
# This script is intended to set up a new Mac computer with my dotfiles and
# other development preferences.
################################################################################


# Thank you, thoughtbot!
bootstrap_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\\n[BOOTSTRAP] $fmt\\n" "$@"
}


################################################################################
# VARIABLE DECLARATIONS
################################################################################

osname=$(uname)
username=$(whoami)

export COMMANDLINE_TOOLS="/Library/Developer/CommandLineTools"
export OLD_DOTFILES_BACKUP=$HOME/old_dotfiles_backup
export DOTFILES_REPO_URL="https://github.com/bartuz/dotfiles.git"
export DOTFILES_DIR=$HOME/dotfiles
export BOOTSTRAP_REPO_URL="https://github.com/bartuz/mac-bootstrap.git"
export BOOTSTRAP_DIR=$HOME/mac-bootstrap

DEFAULT_BOOTSTRAP_BRANCH="master"
DEFAULT_DOTFILES_BRANCH="master"
DEFAULT_COMPUTER_NAME="Filip's mac"
DEFAULT_HOST_NAME="filips-mac"
DEFAULT_TIME_ZONE="Europe/Warsaw"
DEFAULT_NODEJS_VERSION="10.7.0"
DEFAULT_RUBY_VERSION="2.5.1"


################################################################################
# Make sure we're on a Mac before continuing
################################################################################

if [ "$osname" == "Linux" ]; then
  bootstrap_echo "Oops, looks like you're on a Linux machine. Please have a look at
  my Linux Bootstrap script: https://github.com/joshukraine/linux-bootstrap"
  exit 1
elif [ "$osname" != "Darwin" ]; then
  bootstrap_echo "Oops, it looks like you're using a non-UNIX system. This script
only supports Mac. Exiting..."
  exit 1
fi

################################################################################
# Make sure we are on the newest macOS
################################################################################

softwareupdate -i -a

################################################################################
# Check for presence of command line tools if macOS
################################################################################

if [ ! -d "$COMMANDLINE_TOOLS" ]; then
  bootstrap_echo "Apple's command line developer tools must be installed before
running this script. To install them, just run 'xcode-select --install' from
the terminal and then follow the prompts. Once the command line tools have been
installed, you can try running this script again."
  exit 1
fi


################################################################################
# Authenticate
################################################################################

# Keep-alive: update existing `sudo` time stamp until bootstrap has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &


################################################################################
# Welcome and setup
################################################################################

echo
echo "*************************************************************************"
echo "*******                                                           *******"
echo "*******                 Welcome to Mac Bootstrap!                 *******"
echo "*******                                                           *******"
echo "*******                   https://jsua.co/macos                   *******"
echo "*******                                                           *******"
echo "*************************************************************************"
echo

printf "Before we get started, let's get some info about your setup.\\n"

printf "\\nBootstrap script will be cloned from:
==> %s.\\n\\n" "$BOOTSTRAP_REPO_URL"
printf "Which branch should we use? (Leave blank for default: %s)\\n" "$DEFAULT_BOOTSTRAP_BRANCH"
read -r -p "> " BOOTSTRAP_BRANCH
if [ -n "$BOOTSTRAP_BRANCH" ]; then
  export BOOTSTRAP_BRANCH
else
  export BOOTSTRAP_BRANCH="$DEFAULT_BOOTSTRAP_BRANCH"
fi

printf "\\nDotfiles will be cloned from:
==> %s.\\n\\n" "$DOTFILES_REPO_URL"
printf "Which branch should we use? (Leave blank for default: %s)\\n" "$DEFAULT_DOTFILES_BRANCH"
read -r -p "> " DOTFILES_BRANCH
if [ -n "$DOTFILES_BRANCH" ]; then
  export DOTFILES_BRANCH
else
  export DOTFILES_BRANCH="$DEFAULT_DOTFILES_BRANCH"
fi

printf "\\nEnter a name for your Mac. (Leave blank for default: %s)\\n" "$DEFAULT_COMPUTER_NAME"
read -r -p "> " COMPUTER_NAME
export COMPUTER_NAME=${COMPUTER_NAME:-$DEFAULT_COMPUTER_NAME}

printf "\\nEnter a host name for your Mac. (Leave blank for default: %s)\\n" "$DEFAULT_HOST_NAME"
read -r -p "> " HOST_NAME
export HOST_NAME=${HOST_NAME:-$DEFAULT_HOST_NAME}

printf "\\nEnter your desired time zone.
To view available options run \`sudo systemsetup -listtimezones\`
(Leave blank for default: %s)\\n" "$DEFAULT_TIME_ZONE"
read -r -p "> " TIME_ZONE
export TIME_ZONE=${TIME_ZONE:-$DEFAULT_TIME_ZONE}

printf "\\nWhich version of Node.js would you like to install?
Available versions: https://semver.io/node/versions
(Leave blank for default: %s)\\n" "$DEFAULT_NODEJS_VERSION"
read -r -p "> " ASDF_NODEJS_VERSION
export ASDF_NODEJS_VERSION=${ASDF_NODEJS_VERSION:-$DEFAULT_NODEJS_VERSION}

printf "\\nWhich version of Ruby would you like to install?
Available versions: https://raw.githubusercontent.com/postmodern/ruby-versions/master/ruby/versions.txt
(Leave blank for default: %s)\\n" "$DEFAULT_RUBY_VERSION"
read -r -p "> " ASDF_RUBY_VERSION
export ASDF_RUBY_VERSION=${ASDF_RUBY_VERSION:-$DEFAULT_RUBY_VERSION}

printf "\\nLooks good. Here's what we've got so far.\\n"
printf "Bootstrap branch: ==> [%s]\\n" "$BOOTSTRAP_BRANCH"
printf "Dotfiles branch:  ==> [%s]\\n" "$DOTFILES_BRANCH"
printf "Computer name:    ==> [%s]\\n" "$COMPUTER_NAME"
printf "Host name:        ==> [%s]\\n" "$HOST_NAME"
printf "Time zone:        ==> [%s]\\n" "$TIME_ZONE"
printf "Node.js version:  ==> [%s]\\n" "$ASDF_NODEJS_VERSION"
printf "Ruby version:     ==> [%s]\\n" "$ASDF_RUBY_VERSION"

echo
read -p "Continue? (y/n) " -n 1 -r
echo
if [[ ! "$REPLY" =~ ^[Yy]$ ]]; then
  echo "Exiting..."
  exit 1
fi


################################################################################
# Clone mac-bootstrap repo
################################################################################

bootstrap_echo "Cloning mac-bootstrap repo..."
sudo su - "$username" git clone "$BOOTSTRAP_REPO_URL" -b "$BOOTSTRAP_BRANCH" "$BOOTSTRAP_DIR"


################################################################################
# 1. Provision with my adaptation of Laptop (install/laptop)
################################################################################

bootstrap_echo "Step 1: Installing Laptop script..."

sh "$BOOTSTRAP_DIR"/install/laptop 2>&1 | tee ~/laptop.log

bootstrap_echo "Done!"

################################################################################
# 2. Setup dotfiles (http://jsua.co/dotfiles)
################################################################################

bootstrap_echo "Step 3: Installing dotfiles..."

if [[ -d $DOTFILES_DIR ]]; then
  bootstrap_echo "Backing up old dotfiles to $HOME/old_dotfiles_backup..."
  rm -rf "$OLD_DOTFILES_BACKUP"
  cp -R "$DOTFILES_DIR" "$OLD_DOTFILES_BACKUP"
  rm -rf "$DOTFILES_DIR"
fi

bootstrap_echo "Cloning dotfiles repo to ${DOTFILES_DIR} ..."

sudo su - "$username" git clone "$DOTFILES_REPO_URL" -b "$DOTFILES_BRANCH" "$DOTFILES_DIR"

# shellcheck source=/dev/null
source "$DOTFILES_DIR"/install.sh

bootstrap_echo "Done!"

################################################################################
# 3. Set macOS preferences
################################################################################

bootstrap_echo "Checking for SSH key, generating one if it doesn't exist"
[[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

info_echo "Copying public key to clipboard. Paste it into your Github account"
[[ -f ~/.ssh/id_rsa.pub ]] && pbcopy < ~/.ssh/id_rsa.pub
open https://github.com/account/ssh

################################################################################
# 4. Set macOS preferences
################################################################################

bootstrap_echo "Step 8: Setting macOS preferences..."

# shellcheck source=/dev/null
source "$BOOTSTRAP_DIR"/install/macos-defaults

# shellcheck source=/dev/null
source "$BOOTSTRAP_DIR"/install/macos-dock

defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$HOME/dotfiles/iterm2/prefs"
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

rm -rf "$BOOTSTRAP_DIR"

bootstrap_echo "Done!"

################################################################################
# 5.SSH
################################################################################

ssh-keygen -t rsa -b 4096 -C "filip.bartuzi@gmail.com"

rm -rf "$BOOTSTRAP_DIR"

bootstrap_echo "Done!"

echo
echo "**********************************************************************"
echo "**********************************************************************"
echo "****                                                              ****"
echo "**** Mac Bootstrap script complete! Please restart your computer. ****"
echo "****                                                              ****"
echo "****                    https://jsua.co/macos                     ****"
echo "****                                                              ****"
echo "**********************************************************************"
echo "**********************************************************************"
echo
